[build]
  publish = "dist/public"
  command = "node simple-build.js"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  DATABASE_URL = "${DATABASE_URL}"
  DATABASE_PASSWORD = "${DATABASE_PASSWORD}"
  GEMINI_API_KEY = "${GEMINI_API_KEY}"
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"